spring:
  mvc:
    static-path-pattern: /resources/**
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
openweather:
  apiKey: ${OPENWEATHER_API_KEY}
frontend:
  apiKey: ${LOCAL_API_KEY}