
# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy JAR app to Azure Web App - Pocasko

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Set Environment Variables
        run: |
          echo "SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }}" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}" >> $GITHUB_ENV
          echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}" >> $GITHUB_ENV

      #- name : set up node.js
      #  uses: actions/setup-node@v3
      #  with:
      #    node-version: '18.18.2'
      #    npm-version: '10.5.2'

      #- name : Install Angular Cli
      #  run : npm install -g @angular/cli@17.3.5
        #working-directory: ./frontend
#
#      - name: install npm dependencies
#        run: npm install
#        working-directory: ./frontend
#
#      - name: Check versions
#        run: |
#          node --version
#          npm --version
#          ng v
#        working-directory: ./frontend
#
#
#      - name: Build Angular Project
#        run: ng build --base-href "/"
#        working-directory: ./frontend
#
#      - name: Copy angular build artifacts
#        run: |
#          mkdir -p ./src/main/resources/static
#          cp -R ./frontend/dist/frontend/browser/* ./src/main/resources/static/
#        shell : bash
#
#      - name: List files in the static directory
#        run: ls -lah ./src/main/resources/static/
#        shell: bash

      - name: Build and test with Maven
        run: mvn clean install -Pprod

      - name: List contents of JAR
        run: jar tf ./target/*.jar

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
      
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: java-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Pocasko'
          package: '*.jar'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AC3A79652F3748EA9820BB9B26ACB76B }}

